# Generated by Django 3.2.6 on 2021-08-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0003_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
