# Generated by Django 3.2.6 on 2021-08-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0004_alter_weight_entry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='entry_date',
            new_name='date',
        ),
    ]
