# Generated by Django 3.2.3 on 2021-06-04 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followed_by',
            new_name='followers',
        ),
    ]
